# Generated by Django 5.1.1 on 2024-09-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('missing_person_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.SmallIntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='missing_persons/')),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('hair_color', models.CharField(max_length=50)),
                ('eye_color', models.CharField(max_length=50)),
                ('skin_color', models.CharField(max_length=50)),
                ('missing_date', models.DateTimeField()),
                ('location', models.CharField(max_length=50)),
                ('clothes_worn', models.TextField()),
            ],
        ),
    ]
