# Generated by Django 5.1.1 on 2024-09-10 05:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('missing_person_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(default='Unknown', max_length=100)),
                ('age', models.SmallIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='missing_persons/')),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('hair_color', models.CharField(max_length=50)),
                ('eye_color', models.CharField(choices=[('black', 'BLACK'), ('brown', 'BROWN')], default='black', max_length=50)),
                ('skin_color', models.CharField(choices=[('light_skinned', 'Light Skinned'), ('dark_skinned', 'Dark Skinned')], default='dark_skinned', max_length=50)),
                ('missing_date', models.DateTimeField()),
                ('location', models.CharField(max_length=50)),
                ('clothes_worn', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
