# Generated by Django 4.2.16 on 2024-09-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_persons', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='missing_date',
            field=models.DateField(),
        ),
    ]
