# Generated by Django 5.1.1 on 2024-09-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MortuaryStaff',
            fields=[
                ('staff_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=15)),
                ('generated_code', models.CharField(max_length=30)),
            ],
        ),
    ]
