# Generated by Django 5.1 on 2024-09-07 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceOfficer',
            fields=[
                ('officer_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('rank', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=15)),
                ('generated_code', models.CharField(max_length=30)),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.policestation')),
            ],
        ),
    ]
