# Generated by Django 4.2 on 2024-09-14 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mortuary", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MortuaryStaff",
            fields=[
                ("id", models.SmallIntegerField(primary_key=True, serialize=False)),
                ("position", models.CharField(max_length=30)),
                ("contact", models.CharField(max_length=15)),
                ("generated_code", models.CharField(max_length=30)),
                (
                    "mortuary_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mortuary.mortuary",
                    ),
                ),
            ],
        ),
    ]
