# Generated by Django 4.2.16 on 2024-09-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('next_of_kin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextofkin',
            name='address',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='nextofkin',
            name='alternative_contact',
            field=models.CharField(default='Unknown', max_length=15),
        ),
    ]
