# Generated by Django 4.2.16 on 2024-09-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnidentifiedBody',
            fields=[
                ('body_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('skin_color', models.CharField(max_length=50)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('body_marks', models.TextField()),
                ('reporting_date', models.DateTimeField()),
                ('clothes_worn', models.TextField()),
                ('hair_color', models.CharField(max_length=50)),
            ],
        ),
    ]
