# Generated by Django 4.2.16 on 2024-09-10 03:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnidentifiedBody',
            fields=[
                ('body_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('skin_color', models.CharField(choices=[('light_skinned', 'Light Skinned'), ('dark_skinned', 'Dark Skinned')], default='dark_skinned', max_length=50)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('body_marks', models.TextField()),
                ('reporting_date', models.DateTimeField()),
                ('clothes_worn', models.TextField()),
                ('hair_color', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
