# Generated by Django 4.2.16 on 2024-09-09 08:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('unidentified_bodies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidentifiedbody',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='unidentifiedbody',
            name='skin_color',
            field=models.CharField(choices=[('light_skinned', 'Light Skinned'), ('dark_skinned', 'Dark Skinned')], default='dark_skinned', max_length=50),
        ),
    ]
