# Generated by Django 4.2.16 on 2024-09-12 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mortuary_staff', '0001_initial'),
        ('unidentified_bodies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidentifiedbody',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mortuary_staff.mortuarystaff'),
        ),
    ]
