# Generated by Django 4.2 on 2024-09-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mortuary',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('mortuary_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
