name: Django CI/CD

on:
  push:
    branches:
      - feature/cicd-pipeline
  pull_request:
    branches:
      - main
      - staging
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          node-version: 20

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'
          node-version: 20

      - name: Install dependencies
        run: 
          pip install -r requirements.txt

      - name: Run migrations
        run: python manage.py migrate

      - name: Run tests
        run: python manage.py test
